travis:
  secure:
    BINSTAR_TOKEN: nvXrWCEkR4Od4W7n0jxvKdhY0vDp2ZP9HnQsBkmc9fCxw84buS1Rwyg1DnWTJeVYIUDjdNQ7xnteAYe3o58R5nrrc2ERSNbor64Kd9Nn5AZSvwpBfK6qp7EPmdq8HQYtJt4bnW0tzUiRXuk71/ZZHiLYE6ZNg7/mQb7ErQ+J19fb/nwnD+kzy0URqQd4bawT7bUd/Q4asqABHz3H/j/SJl2JDe0f2gJo5J6IOTfm8BBm+8HkmXCplmhJZTzbONWxeips2wdSWrD/R0qL1JD35o31KHiRXaTEGB1TVAwojMkwSU2SF8D6YaylinQEuVX1DtIJD9cvcViuRRFwvOAelE/WOGlupDJTydAPnuh5DgWuqLvTXj57BPLHLXvqLqe6zaIKlKlhETCIyeeH9Ouge7vtbn2GXB7IpvkJfcGtqEQsJWxCv6VtDBAhcYC2M4LDIEEaTBvaUNTdtQdddoIk0bggY32DsP9tstdD0NvfF8rPi9M+2hMXKQs5Gbel8vStU0bB1N44cRk2vgIuObp1lA52ntP5qHx/MkZ4sgQcTFC2nrUxSYRencP8HhZXSC79MNHDFxXKUwyKtxbkUzljfKa0lOC70Zn8Bt1zhs1tbcohAgj4L6ANlLUB/vP50BjIGxOIj4LDF/SofApbhIzc6eeR6Z3VW5S3yT0wuFuKHo0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
